site_description: "PoopOS main website."
site_name: PoopOS
site_url: https://poop-os.github.io
repo_url: https://codeberg.org/poop-os/poop-os.github.io
repo_name: poop-os/poop-os.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  logo: assets/logo.png
  favicon: assets/logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant.progress
    - navigation.tracking
    - content.tooltips

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: ["./news"]

nav:
  - Home:
      - Home: index.md
      - About: about.md
      - FAQ: faq.md
  - Install:
      - Install: install/README.md
  - Blog:
      - Blog: blog/index.md

plugins:
  - macros
  - blog:
      post_excerpt: required
  - rss:
      abstract_delimiter: <!-- more -->
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      use_material_blog: true
