authors:
  joetroll:
    name: Joetroll
    description: Creator
    avatar: https://codeberg.org/joetroll.png
  carnivorecookies:
    name: carnivorecookies
    description: Creator
    avatar: https://codeberg.org/carnivorecookies.png
